defcon_state: 3
party_mode:
  min_lights: 1
  max_lights: 3
  change_delay: 0.5 #Sseconds
gpio_interface:
  sleep_interval: 0.5 #The wait duration between light changes
  pin_layout: BCM #Defines the pin mapping to apply
  pin_map:
    1: 13
    2: 11
    3: 9
    4: 22
    5: 29
  strobe_pin: 0